# Generated by Django 4.1.9 on 2023-10-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('children', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menuapp.menu')),
            ],
        ),
    ]
